# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x03\x61pi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\"#\n\x10LiveImageRequest\x12\x0f\n\x07n_image\x18\x01 \x01(\x05\",\n\rPropertyValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"6\n\x12GetPropertyRequest\x12\x0c\n\x04name\x18\x01 \x03(\t\x12\x12\n\nfrom_cache\x18\x02 \x01(\x08\";\n\x13GetPropertyResponse\x12$\n\x08property\x18\x01 \x03(\x0b\x32\x12.api.PropertyValue\":\n\x12SetPropertyRequest\x12$\n\x08property\x18\x01 \x03(\x0b\x32\x12.api.PropertyValue\"O\n\x13WaitPropertyRequest\x12\x0c\n\x04name\x18\x01 \x03(\t\x12*\n\x07timeout\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\"#\n\x13ListPropertyRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x14ListPropertyResponse\x12\x0c\n\x04name\x18\x01 \x03(\t\"\x15\n\x07ImageID\x12\n\n\x02id\x18\x01 \x01(\t\"\x95\x01\n\x05Image\x12(\n\npixel_type\x18\x01 \x01(\x0e\x32\x14.api.Image.PixelType\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"\"\n\tPixelType\x12\t\n\x05MONO8\x10\x00\x12\n\n\x06MONO16\x10\x01\"3\n\x10SnapImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tsave_file\x18\x02 \x01(\x08\x32\xae\x03\n\x0bNikonTiCtrl\x12\x42\n\x0bGetProperty\x12\x17.api.GetPropertyRequest\x1a\x18.api.GetPropertyResponse\"\x00\x12@\n\x0bSetProperty\x12\x17.api.SetPropertyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x42\n\x0cWaitProperty\x12\x18.api.WaitPropertyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x45\n\x0cListProperty\x12\x18.api.ListPropertyRequest\x1a\x19.api.ListPropertyResponse\"\x00\x12\x32\n\tSnapImage\x12\x15.api.SnapImageRequest\x1a\x0c.api.ImageID\"\x00\x12&\n\x08GetImage\x12\x0c.api.ImageID\x1a\n.api.Image\"\x00\x12\x32\n\tLiveImage\x12\x15.api.LiveImageRequest\x1a\n.api.Image\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])



_IMAGE_PIXELTYPE = _descriptor.EnumDescriptor(
  name='PixelType',
  full_name='api.Image.PixelType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MONO8', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONO16', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=634,
  serialized_end=668,
)
_sym_db.RegisterEnumDescriptor(_IMAGE_PIXELTYPE)


_LIVEIMAGEREQUEST = _descriptor.Descriptor(
  name='LiveImageRequest',
  full_name='api.LiveImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n_image', full_name='api.LiveImageRequest.n_image', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=114,
)


_PROPERTYVALUE = _descriptor.Descriptor(
  name='PropertyValue',
  full_name='api.PropertyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.PropertyValue.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='api.PropertyValue.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=160,
)


_GETPROPERTYREQUEST = _descriptor.Descriptor(
  name='GetPropertyRequest',
  full_name='api.GetPropertyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.GetPropertyRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_cache', full_name='api.GetPropertyRequest.from_cache', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=216,
)


_GETPROPERTYRESPONSE = _descriptor.Descriptor(
  name='GetPropertyResponse',
  full_name='api.GetPropertyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='property', full_name='api.GetPropertyResponse.property', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=277,
)


_SETPROPERTYREQUEST = _descriptor.Descriptor(
  name='SetPropertyRequest',
  full_name='api.SetPropertyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='property', full_name='api.SetPropertyRequest.property', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=337,
)


_WAITPROPERTYREQUEST = _descriptor.Descriptor(
  name='WaitPropertyRequest',
  full_name='api.WaitPropertyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.WaitPropertyRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='api.WaitPropertyRequest.timeout', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=418,
)


_LISTPROPERTYREQUEST = _descriptor.Descriptor(
  name='ListPropertyRequest',
  full_name='api.ListPropertyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.ListPropertyRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=455,
)


_LISTPROPERTYRESPONSE = _descriptor.Descriptor(
  name='ListPropertyResponse',
  full_name='api.ListPropertyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.ListPropertyResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=493,
)


_IMAGEID = _descriptor.Descriptor(
  name='ImageID',
  full_name='api.ImageID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.ImageID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=516,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='api.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixel_type', full_name='api.Image.pixel_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='api.Image.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='api.Image.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='api.Image.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='api.Image.timestamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMAGE_PIXELTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=668,
)


_SNAPIMAGEREQUEST = _descriptor.Descriptor(
  name='SnapImageRequest',
  full_name='api.SnapImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.SnapImageRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='save_file', full_name='api.SnapImageRequest.save_file', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=721,
)

_GETPROPERTYRESPONSE.fields_by_name['property'].message_type = _PROPERTYVALUE
_SETPROPERTYREQUEST.fields_by_name['property'].message_type = _PROPERTYVALUE
_WAITPROPERTYREQUEST.fields_by_name['timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_IMAGE.fields_by_name['pixel_type'].enum_type = _IMAGE_PIXELTYPE
_IMAGE_PIXELTYPE.containing_type = _IMAGE
DESCRIPTOR.message_types_by_name['LiveImageRequest'] = _LIVEIMAGEREQUEST
DESCRIPTOR.message_types_by_name['PropertyValue'] = _PROPERTYVALUE
DESCRIPTOR.message_types_by_name['GetPropertyRequest'] = _GETPROPERTYREQUEST
DESCRIPTOR.message_types_by_name['GetPropertyResponse'] = _GETPROPERTYRESPONSE
DESCRIPTOR.message_types_by_name['SetPropertyRequest'] = _SETPROPERTYREQUEST
DESCRIPTOR.message_types_by_name['WaitPropertyRequest'] = _WAITPROPERTYREQUEST
DESCRIPTOR.message_types_by_name['ListPropertyRequest'] = _LISTPROPERTYREQUEST
DESCRIPTOR.message_types_by_name['ListPropertyResponse'] = _LISTPROPERTYRESPONSE
DESCRIPTOR.message_types_by_name['ImageID'] = _IMAGEID
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['SnapImageRequest'] = _SNAPIMAGEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LiveImageRequest = _reflection.GeneratedProtocolMessageType('LiveImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _LIVEIMAGEREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.LiveImageRequest)
  ))
_sym_db.RegisterMessage(LiveImageRequest)

PropertyValue = _reflection.GeneratedProtocolMessageType('PropertyValue', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTYVALUE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.PropertyValue)
  ))
_sym_db.RegisterMessage(PropertyValue)

GetPropertyRequest = _reflection.GeneratedProtocolMessageType('GetPropertyRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPROPERTYREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.GetPropertyRequest)
  ))
_sym_db.RegisterMessage(GetPropertyRequest)

GetPropertyResponse = _reflection.GeneratedProtocolMessageType('GetPropertyResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPROPERTYRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.GetPropertyResponse)
  ))
_sym_db.RegisterMessage(GetPropertyResponse)

SetPropertyRequest = _reflection.GeneratedProtocolMessageType('SetPropertyRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETPROPERTYREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.SetPropertyRequest)
  ))
_sym_db.RegisterMessage(SetPropertyRequest)

WaitPropertyRequest = _reflection.GeneratedProtocolMessageType('WaitPropertyRequest', (_message.Message,), dict(
  DESCRIPTOR = _WAITPROPERTYREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.WaitPropertyRequest)
  ))
_sym_db.RegisterMessage(WaitPropertyRequest)

ListPropertyRequest = _reflection.GeneratedProtocolMessageType('ListPropertyRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTPROPERTYREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ListPropertyRequest)
  ))
_sym_db.RegisterMessage(ListPropertyRequest)

ListPropertyResponse = _reflection.GeneratedProtocolMessageType('ListPropertyResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTPROPERTYRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ListPropertyResponse)
  ))
_sym_db.RegisterMessage(ListPropertyResponse)

ImageID = _reflection.GeneratedProtocolMessageType('ImageID', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEID,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ImageID)
  ))
_sym_db.RegisterMessage(ImageID)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Image)
  ))
_sym_db.RegisterMessage(Image)

SnapImageRequest = _reflection.GeneratedProtocolMessageType('SnapImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _SNAPIMAGEREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.SnapImageRequest)
  ))
_sym_db.RegisterMessage(SnapImageRequest)



_NIKONTICTRL = _descriptor.ServiceDescriptor(
  name='NikonTiCtrl',
  full_name='api.NikonTiCtrl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=724,
  serialized_end=1154,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProperty',
    full_name='api.NikonTiCtrl.GetProperty',
    index=0,
    containing_service=None,
    input_type=_GETPROPERTYREQUEST,
    output_type=_GETPROPERTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetProperty',
    full_name='api.NikonTiCtrl.SetProperty',
    index=1,
    containing_service=None,
    input_type=_SETPROPERTYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WaitProperty',
    full_name='api.NikonTiCtrl.WaitProperty',
    index=2,
    containing_service=None,
    input_type=_WAITPROPERTYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListProperty',
    full_name='api.NikonTiCtrl.ListProperty',
    index=3,
    containing_service=None,
    input_type=_LISTPROPERTYREQUEST,
    output_type=_LISTPROPERTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SnapImage',
    full_name='api.NikonTiCtrl.SnapImage',
    index=4,
    containing_service=None,
    input_type=_SNAPIMAGEREQUEST,
    output_type=_IMAGEID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetImage',
    full_name='api.NikonTiCtrl.GetImage',
    index=5,
    containing_service=None,
    input_type=_IMAGEID,
    output_type=_IMAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LiveImage',
    full_name='api.NikonTiCtrl.LiveImage',
    index=6,
    containing_service=None,
    input_type=_LIVEIMAGEREQUEST,
    output_type=_IMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NIKONTICTRL)

DESCRIPTOR.services_by_name['NikonTiCtrl'] = _NIKONTICTRL

# @@protoc_insertion_point(module_scope)
